apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: insecure-web-6d78b6d8dd
  namespace: podsec-only
spec:
  template:
    spec:
      containers:
        - name: web
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      securityContext:
        seccompProfile:
          type: RuntimeDefault