apiVersion: v1
kind: Pod
metadata:
  name: victim
  namespace: default
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 1000
  containers:
    - name: victim
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL