apiVersion: v1
kind: Namespace
metadata:
  name: cve-2023-2431
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: cve-2023-2431
  labels:
    app: my-app
spec:
  containers:
    - name: my-nginx
      image: nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ['ALL']
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: poc-pod
  namespace: cve-2023-2431
  labels:
    app: my-app
spec:
  containers:
    - name: poc-pod
      image: nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ['ALL']
        runAsNonRoot: true
        seccompProfile:
          type: Localhost
          localhostProfile: ""

