apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payments-api-default-deny-ingress
  namespace: payments
spec:
  podSelector:
    matchLabels:
      app: payments-api
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: payments-api
  policyTypes:
  - Ingress