apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payments-api-778b99cbdd
  namespace: payments
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: payments-api
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL