apiVersion: v1
kind: Pod
metadata:
  name: nginx-858ddf8b75-sfvd7
  namespace: demo
spec:
  containers:
  - name: nginx
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
  securityContext:
    seccompProfile:
      type: RuntimeDefault