apiVersion: v1
kind: Namespace
metadata:
  name: rbac-podsec
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: rbac-podsec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: rbac-podsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: rbac-podsec
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-overperm
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-overperm-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-overperm
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    namespace: rbac-podsec

