apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: widgets.example.com
spec:
  group: example.com
  version: v1
  scope: Cluster
  names:
    plural: widgets
    singular: widget
    kind: Widget
---
apiVersion: example.com/v1
kind: Widget
metadata:
  name: cluster-widget
spec:
  value: "top-secret"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poc
  namespace: tenant-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: widget-reader
  namespace: tenant-a
rules:
  - apiGroups: ["example.com"]
    resources: ["widgets"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: widget-reader-binding
  namespace: tenant-a
subjects:
  - kind: ServiceAccount
    name: poc
    namespace: tenant-a
roleRef:
  kind: Role
  name: widget-reader
  apiGroup: rbac.authorization.k8s.io

