apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: rbac-podsec
spec:
  template:
    spec:
      containers:
      - name: nginx
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      securityContext:
        seccompProfile:
          type: RuntimeDefault