apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-7f8979d8b5
  namespace: podsec-only
spec:
  template:
    spec:
      containers:
        - name: nginx
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        seccompProfile:
          type: RuntimeDefault