apiVersion: v1
kind: Namespace
metadata:
  name: kubeproxy-mitm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: kubeproxy-mitm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: ealen/echo-server:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mitm-lb
  namespace: kubeproxy-mitm
spec:
  selector:
    app: echoserver
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  externalIPs:
    - 8.8.8.8
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: victim
  namespace: default
  labels:
    app: victim
spec:
  containers:
    - name: victim
      image: busybox
      command: ["sh", "-c", "sleep 3600"]

